caterwaul.module( 'jquery-node' ,function($) {$.jquery_nodejs_element=function(tag) {;
return(function(it) {return it._tag=tag,it._classes= [] ,it._attributes= {} ,it._children= [] ,it} ) .call(this, (this) ) } ,$.merge($.jquery_nodejs_element.prototype, {toString:function() {;
return( '<' + (this._tag) + '' + (this.class_string() ) + '' + (this.attribute_string() ) + '>' + (this.children_string() ) + '</' + (this._tag) + '>' ) } ,attribute_string:function() {;
return(function(it) {return it.join( '' ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( ( ' ' + (x[0] ) + '="' ) +x[1] .replace( /"/g , '\\"' ) + '"' ) ) ;
return xr} ) .call(this, (function(o) {var ps= [] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (this._attributes) ) ) ) ) } ,children_string:function() {;
return(function(it) {return it.join( '' ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.toString() ) ) ;
return xr} ) .call(this,this._children) ) ) } ,class_string:function() {;
return this._classes.length? ( ' class="' + (this._classes.join( " " ) ) + '"' ) : '' } ,append:function() {var xs=arguments;
return(function(it) {return it._children=it._children.concat(Array.prototype.slice.call( (xs) ) ) ,it} ) .call(this, (this) ) } ,addClass:function(c) {;
return(function(it) {return(it._classes) .push(c) ,it} ) .call(this, (this) ) } ,attr:function(k,v) {;
return(function(it) {return it._attributes[k] =v,it} ) .call(this, (this) ) } ,text:function(t) {;
return(function(it) {return it._children= [t.replace( /&/g , '&amp;' ) .replace( /</g , '&lt;' ) .replace( />/g , '&gt;' ) ] ,it} ) .call(this, (this) ) } } ) ,$.jquery_nodejs=function(xs) {;
return(function(it) {return it._elements=xs,it} ) .call(this, (this) ) } ,$.merge($.jquery_nodejs.prototype, {toString:function() {;
return this._elements.join( '' ) } ,append:function() {var xs=arguments;
return(function(it) {return it._elements.length&&it._elements[0] .append.apply(it._elements[0] ,xs) ,it} ) .call(this, (this) ) } ,addClass:function(c) {;
return(function(it) {return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .addClass(c) ) ;
return xs} ) .call(this,it._elements) ,it} ) .call(this, (this) ) } ,attr:function(k,v) {;
return(function(it) {return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (x.attr(k,v) ) ;
return xs} ) .call(this,it._elements) ,it} ) .call(this, (this) ) } ,text:function(t) {;
return(function(it) {return(function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .text(t) ) ;
return xs} ) .call(this,it._elements) ,it} ) .call(this, (this) ) } ,add:function(x) {;
return new $.jquery_nodejs( (this._elements) .concat( ( [x] ) ) ) } } ) ,jQuery=function(tag) {;
return(function(it) {return it?new $.jquery_nodejs( [new $.jquery_nodejs_element( 'span' ) ] ) .append(it[1] ) :new $.jquery_nodejs( [new $.jquery_nodejs_element(tag.replace( /^<(.*)>$/ , '$1' ) ) ] ) } ) .call(this, ( /^<span>(.*)<\/span>$/ .exec(tag) ) ) } } ) ;
